theme = "gruvbox"

[editor]
line-number = "relative"
mouse = true
middle-click-paste = true
scroll-lines = 3
bufferline = "multiple"
color-modes = true
true-color = true
cursorline = true
auto-save = true
auto-format = true
idle-timeout = 200

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = []
right = ["diagnostics", "selections", "position", "file-encoding"]

[editor.lsp]
display-messages = true
